fix(docs): fix typescript doc issues
AirCodeLabs/aircode pull request #68
Opened 2023-06-29 05:37 UTC by niudai

2023-06-29 05:41 UTC, adcentury requested changes

2023-06-29 05:41 UTC, adcentury commented on docs/en/src/guide/functions/index.md
> +- [Using Typescript](/guide/functions/typescript)
Should be `TypeScript`, not `Typescript`

2023-06-29 05:41 UTC, adcentury requested changes

2023-06-29 05:41 UTC, adcentury commented on docs/zh-cn/src/guide/functions/index.md
> +- [使用 Typescript](/guide/functions/typescript)
Same typo here.

2023-07-03 08:27 UTC, niudai commented
已改

2023-07-04 05:54 UTC, adcentury approved these changes
LGTM.

2023-07-04 05:55 UTC, merged